### ISSUE TITLE
[BU-163]Duomenų gavimo formoje išimame el. pašto lauką

### ISSUE THREAD

**Issue by ambrazasp** [AplinkosMinisterija/biip-uetk-web#54]
**Duomenų gavimo formoje:**
1.išimame el. pašto lauką. 
2.Virš formos pateikiame informacinį pranešimą kaip pvz.

**Duomenų teikimo formoje:**
1.Virš formos pateikiame informacinį pranešimą kaip pvz.

![Image](https://github.com/user-attachments/assets/ea07e33d-43bb-45b4-a239-2ecb5aa4d611)

**Comment by IngaPauliuniene** [comment]
Užduotis nėra atlikta iki galo
Nepadaryta ši dalis 

Duomenų teikimo formoje:
1.Virš formos pateikiame informacinį pranešimą kaip pvz.
![Image](https://github.com/user-attachments/assets/15958d9c-0131-4385-8f81-3fc709026d16)
